# Generated by Django 4.1.2 on 2022-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_picture1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='borough',
        ),
        migrations.AddField(
            model_name='listing',
            name='archdeaconry',
            field=models.CharField(blank=True, choices=[('Mathews Cathedral Archdeaconry', 'Mathews Cathedral Archdeaconry'), ('Emmanuel Archdeaconry', 'Emmanuel Archdeaconry')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parish',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
